# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.yandex_map = QtWidgets.QTextBrowser(self.centralwidget)
        self.yandex_map.setGeometry(QtCore.QRect(10, 10, 561, 401))
        self.yandex_map.setObjectName("yandex_map")
        self.schemeButton = QtWidgets.QPushButton(self.centralwidget)
        self.schemeButton.setGeometry(QtCore.QRect(590, 10, 101, 31))
        self.schemeButton.setObjectName("schemeButton")
        self.satteliteButton = QtWidgets.QPushButton(self.centralwidget)
        self.satteliteButton.setGeometry(QtCore.QRect(590, 50, 101, 31))
        self.satteliteButton.setObjectName("satteliteButton")
        self.hybridButton = QtWidgets.QPushButton(self.centralwidget)
        self.hybridButton.setGeometry(QtCore.QRect(590, 90, 101, 31))
        self.hybridButton.setObjectName("hybridButton")
        self.input_text = QtWidgets.QLineEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(150, 420, 421, 21))
        self.input_text.setObjectName("input_text")
        self.Input_name = QtWidgets.QLabel(self.centralwidget)
        self.Input_name.setGeometry(QtCore.QRect(10, 420, 121, 16))
        self.Input_name.setObjectName("Input_name")
        self.findButton = QtWidgets.QPushButton(self.centralwidget)
        self.findButton.setGeometry(QtCore.QRect(580, 420, 111, 21))
        self.findButton.setObjectName("findButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(580, 480, 111, 31))
        self.clearButton.setObjectName("clearButton")
        self.output_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(150, 480, 421, 31))
        self.output_text.setMouseTracking(True)
        self.output_text.setObjectName("output_text")
        self.output_name = QtWidgets.QLabel(self.centralwidget)
        self.output_name.setGeometry(QtCore.QRect(10, 480, 101, 31))
        self.output_name.setObjectName("output_name")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 450, 101, 21))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.schemeButton.setText(_translate("MainWindow", "Scheme"))
        self.satteliteButton.setText(_translate("MainWindow", "Satettite"))
        self.hybridButton.setText(_translate("MainWindow", "Hybrid"))
        self.Input_name.setText(_translate("MainWindow", "Введите запрос:"))
        self.findButton.setText(_translate("MainWindow", "Find"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.output_name.setText(_translate("MainWindow", "Полный адрес:"))
        self.checkBox.setText(_translate("MainWindow", "postal code"))
